version: '3.8'

networks:
  db:

services:
  db:
    image: postgres
    restart: always   
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: dbProjeto
    ports:
      - "5432:5432"
    volumes:
      - './data:/var/lib/postgresql/data'
    networks:
      - db
    expose:
      - "5432"
  web:
    image: nginx
    container_name: servidor-nginx
    ports:
      - "8080:80"
    volumes:
      - './ProjetoGeo:/usr/share/nginx/html'

